#!/bin/sh

# Loop through all attached batteries.
for battery in /sys/class/power_supply/BAT?*; do

    # If non-first battery, print a space separator.
    [ -n "${capacity+x}" ] && printf " "
    capacity="$(cat "$battery/capacity" 2>&1)"

    # Setting battery icon based on % battery
    if [ "$capacity" -gt 90 ]; then
        baticon=" "
    elif [ "$capacity" -gt 60 ]; then
        baticon=" "
    elif [ "$capacity" -gt 40 ]; then
        baticon=" "
    elif [ "$capacity" -gt 10 ]; then
        baticon=" "
    else
        baticon=" "
    fi
    case "$(cat "$battery/status" 2>&1)" in
        Full) baticon=" " ;;
        Discharging)
            if [ "$capacity" -le 20 ]; then
                baticon="$baticon"
                color=1
            fi
            ;;
        Charging) baticon="󰚥$baticon" ;;
        "Not charging") baticon=" " ;;
        Unknown) baticon="? $baticon" ;;
        *) exit 1 ;;
    esac

    echo $baticon$capacity"%"
done
