[general]
import = [
  "~/.config/alacritty/themes/themes/alabaster_dark.toml"
]

[window]
decorations = "None"
dimensions = { columns = 100 , lines = 25 }
position = { x = 450 , y = 250 }
padding = { x = 3, y = 10 }
class = { instance = "floating" , general = "Alacritty-float" }
dynamic_padding = true

[font]
normal = { family = "ComicShannsMonoNerdFont", style = "Regular" }
bold = { family = "ComicShannsMonoNerdFont", style = "Bold" }
italic = { family = "ComicShannsMonoNerdFont", style = "Italic" }
size = 11.5

[terminal.shell]
program = "/usr/bin/zsh"
