import = [
  "~/.config/alacritty/themes/themes/orangish.toml"
]

[window]
decorations = "None"
dimensions = { columns = 100 , lines = 25 }
position = { x = 450 , y = 250 }
padding = { x = 3, y = 10 }
class = { instance = "floating" , general = "Alacritty" }
dynamic_padding = true
opacity = 0.70

[font]
normal = { family = "JetBrainsMonoNF", style = "Regular" }
bold = { family = "JetBrainsMonoNF", style = "Bold" }
italic = { family = "JetBrainsMonoNF", style = "Italic" }
size = 11.5

[shell]
program = "/usr/bin/zsh"
