[window]
decorations = "None"
dimensions = { columns = 100 , lines = 25 }
padding = { x = 3, y = 3 }
dynamic_padding = true
startup_mode = "maximized"
# opacity = 0.80

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
bold = { family = "JetBrainsMonoNerdFont", style = "Bold" }
italic = { family = "JetBrainsMonoNerdFont", style = "Italic" }
size = 14

 [general]
 import = [
   "~/.config/alacritty/themes/themes/everfrost_dark.toml"
 ]

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-c", "tmux -u attach || tmux -u new -s init"]
